#!/bin/bash

# list picks inside the picks array
# ignores any element that starts with #
# supports:
#           12345       <-- pick a specific commit
#           -twhatever  <-- picks topic 'whatever' (intentionally no space in there)

picks=(
# external/stlport
158215
# system/sepolicy
158310
# vendor/cm
158322
# build
158337
# hardware/libhardware
158286
# packages/providers/TelephonyProvider
158465
158466
)

[ ! -f build/envsetup.sh ] && echo "Nah, you don't appear to be at the top of your source tree!" && exit 1

source build/envsetup.sh

for p in ${picks[@]}; do
  if [[ ${p:0:1} == '#' ]]; then
    continue
  elif [[ ${p:0:2} == '-t' ]]; then
    t=`echo $p | sed -r 's/^.{2}//'`
    repopick -t $t
  else
    repopick $p
  fi
done
